// SPDX-FileCopyrightText: 2026 Jonas Kaninda
// SPDX-License-Identifier: AGPL-3.0-or-later

// Command mwdocsgen writes the middleware reference pages for the documentation
// site from the middleware catalog.
//
// The catalog already carries every field's label, type, default, options and
// help text — it is what the API returns and what the console's form renders
// from. Hand-writing twenty pages of the same information guarantees the two
// disagree within a release, and the docs are the copy nobody notices going
// stale. So the reference is generated, and a test asserts the committed pages
// match the catalog.
//
// Prose that is not derivable — what a middleware is for, when to reach for it —
// lives in the hand-written overview page, which this does not touch.
//
//	go run ./cmd/mwdocsgen -o ../docs/docs/middlewares
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/miabi-io/miabi/internal/mwcatalog"
)

func main() {
	out := flag.String("o", "../docs/docs/middlewares", "directory to write the reference pages into")
	flag.Parse()

	if err := run(*out); err != nil {
		fmt.Fprintln(os.Stderr, "mwdocsgen:", err)
		os.Exit(1)
	}
}

func run(dir string) error {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	pages, err := Pages()
	if err != nil {
		return err
	}
	for name, body := range pages {
		if err := os.WriteFile(filepath.Join(dir, name), []byte(body), 0o644); err != nil {
			return err
		}
	}
	fmt.Printf("mwdocsgen: wrote %d pages to %s\n", len(pages), dir)
	return nil
}

func Pages() (map[string]string, error) {
	descs := mwcatalog.All()
	pages := make(map[string]string, len(descs)+1)
	for i, d := range descs {
		pages[FileName(d.Type)] = page(d, i+3)
	}
	pages["reference.md"] = indexPage(descs)
	return pages, nil
}

// FileName is the page a middleware type is documented in.
func FileName(t string) string { return Slug(t) + ".md" }

func Slug(t string) string {
	var b strings.Builder
	for i, r := range t {
		if r >= 'A' && r <= 'Z' {
			if i > 0 {
				b.WriteByte('-')
			}
			b.WriteRune(r - 'A' + 'a')
			continue
		}
		b.WriteRune(r)
	}
	return b.String()
}

var categoryLabel = map[mwcatalog.Category]string{
	mwcatalog.CategoryAccess:        "Access",
	mwcatalog.CategorySecurity:      "Security",
	mwcatalog.CategoryTraffic:       "Traffic",
	mwcatalog.CategoryTransform:     "Transform",
	mwcatalog.CategoryObservability: "Observability",
}

func page(d mwcatalog.Descriptor, position int) string {
	var b strings.Builder

	fmt.Fprintf(&b, "---\nsidebar_position: %d\ntitle: %s\ndescription: %s\n---\n\n", position, d.DisplayName, escapeYAML(d.Description))
	fmt.Fprintf(&b, "<!-- Generated by cmd/mwdocsgen from internal/mwcatalog. Do not edit by hand. -->\n\n")
	fmt.Fprintf(&b, "# %s\n\n%s\n\n", d.DisplayName, d.Description)

	fmt.Fprintf(&b, "| | |\n|---|---|\n")
	fmt.Fprintf(&b, "| **Type** | `%s` |\n", d.Type)
	fmt.Fprintf(&b, "| **Category** | %s |\n", categoryLabel[d.Category])
	if d.MinGatewayVersion != "" {
		fmt.Fprintf(&b, "| **Requires** | Goma Gateway %s or newer |\n", d.MinGatewayVersion)
	}
	if d.DocsURL != "" {
		fmt.Fprintf(&b, "| **Gateway reference** | [%s](%s) |\n", gatewayLinkLabel(d), d.DocsURL)
	}
	b.WriteString("\n")

	if d.MinGatewayVersion != "" {
		fmt.Fprintf(&b, ":::warning Gateway version\nA route using this middleware fails to load on a gateway older than **%s**. "+
			"Miabi does not read the running gateway's version, so nothing stops you saving it — the route is what reports the problem.\n:::\n\n",
			d.MinGatewayVersion)
	}

	b.WriteString("## Fields\n\n")
	writeFieldTable(&b, d.Fields)

	writeNested(&b, d.Fields, nil, 3)

	if hasSecret(d.Fields) {
		b.WriteString("\n:::note Secret fields\nFields marked **secret** are encrypted at rest and never returned by the API. " +
			"Editing the middleware leaves a stored secret in place unless you type a new value — an empty box means \"keep what is stored\", not \"clear it\".\n:::\n")
	}
	return b.String()
}

func gatewayLinkLabel(d mwcatalog.Descriptor) string {
	if strings.HasSuffix(d.DocsURL, "/middlewares/") {
		return "Goma middleware reference"
	}
	return "Goma docs: " + d.Type
}

func writeFieldTable(b *strings.Builder, fields []mwcatalog.Field) {
	b.WriteString("| Field | Type | Required | Default | Description |\n|---|---|---|---|---|\n")
	for _, f := range fields {
		fmt.Fprintf(b, "| `%s` | %s | %s | %s | %s |\n",
			f.Key, fieldType(f), yesNo(f.Required), defaultOf(f), describe(f))
	}
}

// writeNested emits a table per object/list sub-schema, depth-first.
func writeNested(b *strings.Builder, fields []mwcatalog.Field, path []string, heading int) {
	for _, f := range fields {
		if len(f.Fields) == 0 {
			continue
		}
		here := append(append([]string{}, path...), f.Key)
		fmt.Fprintf(b, "\n%s `%s`\n\n", strings.Repeat("#", heading), strings.Join(here, "."))
		if f.Help != "" {
			fmt.Fprintf(b, "%s\n\n", f.Help)
		}
		if f.Type == mwcatalog.FieldList {
			fmt.Fprintf(b, "A list; each entry has these fields.\n\n")
		}
		writeFieldTable(b, f.Fields)
		writeNested(b, f.Fields, here, heading+1)
	}
}

func fieldType(f mwcatalog.Field) string {
	switch f.Type {
	case mwcatalog.FieldEnum:
		quoted := make([]string, len(f.Options))
		for i, o := range f.Options {
			quoted[i] = "`" + o + "`"
		}
		return "one of " + strings.Join(quoted, ", ")
	case mwcatalog.FieldStrings:
		return "list of text"
	case mwcatalog.FieldInts:
		return "list of numbers"
	case mwcatalog.FieldDuration:
		return "duration (e.g. `10m`)"
	case mwcatalog.FieldMap:
		return "key/value map"
	case mwcatalog.FieldPairs:
		return "key/value pairs"
	case mwcatalog.FieldUsers:
		return "username/password pairs"
	case mwcatalog.FieldObject:
		return "group"
	case mwcatalog.FieldList:
		return "list of groups"
	case mwcatalog.FieldBool:
		return "true/false"
	case mwcatalog.FieldInt:
		return "number"
	default:
		return "text"
	}
}

func yesNo(v bool) string {
	if v {
		return "**yes**"
	}
	return "no"
}

func defaultOf(f mwcatalog.Field) string {
	if f.Default == nil {
		return "—"
	}
	return fmt.Sprintf("`%v`", f.Default)
}

func describe(f mwcatalog.Field) string {
	parts := []string{}
	if h := strings.TrimSpace(f.Help); h != "" {
		parts = append(parts, escapeMD(h))
	} else if f.Label != "" {
		parts = append(parts, escapeMD(f.Label)+".")
	}
	if f.Secret {
		parts = append(parts, "**Secret** — encrypted at rest, never returned by the API.")
	}
	if f.Placeholder != "" {
		parts = append(parts, "Example: `"+escapeMD(f.Placeholder)+"`.")
	}
	if len(parts) == 0 {
		return "—"
	}
	return strings.Join(parts, " ")
}

func hasSecret(fields []mwcatalog.Field) bool {
	for _, f := range fields {
		if f.Secret || hasSecret(f.Fields) {
			return true
		}
	}
	return false
}

func indexPage(descs []mwcatalog.Descriptor) string {
	var b strings.Builder
	b.WriteString("---\nsidebar_position: 2\ntitle: All middlewares\ndescription: Every middleware type Miabi curates, what it does, and which category it belongs to.\n---\n\n")
	b.WriteString("<!-- Generated by cmd/mwdocsgen from internal/mwcatalog. Do not edit by hand. -->\n\n")
	b.WriteString("# All middlewares\n\n")
	b.WriteString("Every middleware type Miabi curates. Each has a form in the console, validation on save, and " +
		"encryption for any field holding a credential. See [Using middlewares](/docs/middlewares/overview) for how to " +
		"attach them to a route and why the order matters.\n\n")

	byCat := map[mwcatalog.Category][]mwcatalog.Descriptor{}
	var order []mwcatalog.Category
	for _, d := range descs {
		if _, seen := byCat[d.Category]; !seen {
			order = append(order, d.Category)
		}
		byCat[d.Category] = append(byCat[d.Category], d)
	}
	sort.SliceStable(order, func(i, j int) bool { return categoryRank(order[i]) < categoryRank(order[j]) })

	for _, cat := range order {
		fmt.Fprintf(&b, "## %s\n\n| Middleware | Type | What it does |\n|---|---|---|\n", categoryLabel[cat])
		for _, d := range byCat[cat] {
			fmt.Fprintf(&b, "| [%s](/docs/middlewares/%s) | `%s` | %s |\n",
				d.DisplayName, Slug(d.Type), d.Type, escapeMD(d.Description))
		}
		b.WriteString("\n")
	}

	b.WriteString(":::note Uncatalogued types\nA middleware type Miabi does not curate can still be used: the rule is passed to the " +
		"gateway as written. It gets no form, no validation and no encryption of its fields, so a credential in one is stored in the clear. " +
		"Prefer a curated type where one exists.\n:::\n")
	return b.String()
}

func categoryRank(c mwcatalog.Category) int {
	for i, x := range []mwcatalog.Category{
		mwcatalog.CategoryAccess, mwcatalog.CategorySecurity, mwcatalog.CategoryTraffic,
		mwcatalog.CategoryTransform, mwcatalog.CategoryObservability,
	} {
		if x == c {
			return i
		}
	}
	return 99
}

// escapeMD makes catalog prose safe inside an MDX table cell.
//
// A pipe would split the cell. Braces are worse: MDX reads `{` as the start of a
// JSX expression, so a help string mentioning a `{{ .claim }}` template fails the
// whole docs build rather than rendering oddly. Escaped as entities because no
// help text uses code spans, where the braces would have been literal anyway.
func escapeMD(s string) string {
	r := strings.NewReplacer(
		"|", `\|`,
		"{", "&#123;",
		"}", "&#125;",
		"<", "&lt;",
		">", "&gt;",
	)
	return r.Replace(s)
}

// escapeYAML quotes a frontmatter value that would otherwise break the document.
func escapeYAML(s string) string {
	if strings.ContainsAny(s, `:#"'`) {
		return `"` + strings.ReplaceAll(s, `"`, `\"`) + `"`
	}
	return s
}
