// SPDX-FileCopyrightText: 2026 Jonas Kaninda
// SPDX-License-Identifier: AGPL-3.0-or-later

// Turns src/theme/accents.json into src/assets/accents.css.
//
// The default accent is not emitted: it already lives in styles.css as the :root
// ramp, so emitting it again would mean two places to change one colour.
//
//   npm run gen:accents
//
// It also runs as `prebuild`, so the shipped stylesheet is always the JSON's
// current output and a forgotten run cannot reach production. The generated file
// is committed anyway, so `npm run dev` needs no build step first.

import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const source = join(here, '..', 'src', 'theme', 'accents.json')
const target = join(here, '..', 'src', 'assets', 'accents.css')

const STEPS = ['50', '100', '200', '300', '400', '500', '600', '700', '800', '900']

export function renderAccents(accents) {
  const out = [
    '/* Generated by scripts/gen-accents.mjs from src/theme/accents.json.',
    '   Do not edit: run `npm run gen:accents`. */',
    '',
  ]
  for (const a of accents) {
    if (a.code === 'default') continue // already the :root ramp in styles.css
    out.push(`[data-accent="${a.code}"] {`)
    for (const step of STEPS) out.push(`  --primary-${step}: ${a.ramp[step]};`)
    out.push('}', '')
    // Only the -50 tint inverts for a dark ground; 100-900 read on both.
    out.push(`[data-theme="dark"][data-accent="${a.code}"] {`)
    out.push(`  --primary-50: ${a.dark50};`)
    out.push('}', '')
  }
  return out.join('\n')
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const { accents } = JSON.parse(readFileSync(source, 'utf8'))
  writeFileSync(target, renderAccents(accents))
  console.log(`wrote ${target} (${accents.length - 1} accents)`)
}
